namespace IQIAIndicator.Tests.GoldenDatasets;

/// <summary>
/// Sprint 15 / Part L. A single, central catalog of synthetic price series shared across the
/// Engine/Regime/Evidence model validation tests.
///
/// Every series here is a PRICE series (decimal, always &gt; 0, oldest-first) - exactly the shape
/// `EvidenceContext.Series` carries in production (RegimeEngine feeds it a rolling window of
/// `context.Price.Close` values; see Engine/Regime/RegimeEngine.cs). This is deliberately different
/// from several of the per-model GoldenDataset classes (e.g. DfaGoldenDataset.WhiteNoise, which
/// returns raw N(0,1) values used AS IF they were already a return series) - those remain valid for
/// their own models' internal validation, but are not safe to feed into a different model's
/// EvidenceContext.Series without re-deriving their semantics. This catalog exists so that
/// cross-model tests (ADF vs KPSS agreement, Hurst-proxy vs DFA-Hurst comparison, edge cases applied
/// uniformly across all nine models) all operate on the exact same, exactly reproducible inputs.
///
/// Determinism: every series is generated by the same 64-bit LCG + Box-Muller Gaussian generator
/// already used throughout Tests/GoldenDatasets (Ad fGoldenDataset, KpssGoldenDataset, etc.), always
/// seeded explicitly (default seed = 42). No unseeded System.Random is used anywhere in this file, so
/// every run of every test using this catalog reproduces byte-identical series (Part L / rule 10:
/// reproducibility).
/// </summary>
public static class SyntheticSeriesCatalog
{
    /// <summary>Dataset 01 - Constant: every value identical. Degenerate case: zero variance, zero autocovariance, undefined regression slope denominators.</summary>
    public static decimal[] Constant(int length = 120, decimal level = 100m)
    {
        var series = new decimal[length];
        Array.Fill(series, level);
        return series;
    }

    /// <summary>Dataset 02 - White Noise: level_t = 100 + N(0, sigma), i.i.d., NOT cumulative. Stationary in level by construction (no unit root, no trend, no memory).</summary>
    public static decimal[] WhiteNoise(int length = 120, ulong seed = 42UL, decimal sigma = 1.0m)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var series = new decimal[length];
        for (int i = 0; i < length; i++)
            series[i] = 100m + sigma * noise[i];
        return series;
    }

    /// <summary>
    /// Dataset 03 - Random Walk: ADDITIVE random walk, price_t = price_{t-1} + eps_t, matching the
    /// exact convention already established and validated in AdfGoldenDataset.RandomWalk /
    /// KpssGoldenDataset.RandomWalk (both documented there as producing reliable non-stationarity
    /// detection under both tests). Unit root by construction.
    ///
    /// Design note (Part O style, documenting a real fixture-design finding from this sprint, not a
    /// model defect): an earlier version of this dataset used a GEOMETRIC random walk
    /// (price_t = price_{t-1} * exp(sigma * z_t)). That formulation is unstable for tests that run
    /// ADF/KPSS directly on the price LEVEL (rather than on log-returns): the exponential transform
    /// means ADF's t-statistic is not simply invariant to a sigma rescaling the way it would be under
    /// a pure additive/linear transform, so an arbitrarily-chosen sigma could push the realized path
    /// into an ambiguous zone for one test or the other. The additive formulation avoids this
    /// entirely and is the same one this project's own ADF/KPSS golden datasets already rely on.
    /// </summary>
    public static decimal[] RandomWalk(int length = 120, ulong seed = 42UL, decimal sigma = 1.0m)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var series = new decimal[length];
        series[0] = 100m;
        for (int i = 1; i < length; i++)
            series[i] = series[i - 1] + sigma * noise[i];
        return series;
    }

    /// <summary>Dataset 04 - AR(1), phi=0.5: level_t = phi*level_{t-1} + N(0,1); price_t = 100 + level_t. Stationary, moderate short-memory persistence.</summary>
    public static decimal[] Ar1(int length = 120, ulong seed = 42UL, decimal phi = 0.5m)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var level = new decimal[length];
        for (int i = 1; i < length; i++)
            level[i] = phi * level[i - 1] + noise[i];
        var series = new decimal[length];
        for (int i = 0; i < length; i++)
            series[i] = 100m + level[i];
        return series;
    }

    /// <summary>Dataset 05 - Mean-Reverting OU (discrete, kappa=0.5): deviation_t = deviation_{t-1} + kappa*(0-deviation_{t-1}) + N(0,1); price_t = 100 + deviation_t. Strongly stationary, short half-life (theoretical HalfLife = ln(2)/0.5 ~= 1.386 bars for the *continuous* analogue; the discrete AR(1) coefficient is (1-kappa)=0.5, so HalfLifeStatistics' own OLS on this series should recover lambda near -kappa=-0.5).</summary>
    public static decimal[] MeanRevertingOu(int length = 120, ulong seed = 42UL, decimal kappa = 0.5m)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var deviation = new decimal[length];
        for (int i = 1; i < length; i++)
            deviation[i] = deviation[i - 1] + kappa * (0m - deviation[i - 1]) + noise[i];
        var series = new decimal[length];
        for (int i = 0; i < length; i++)
            series[i] = 100m + deviation[i];
        return series;
    }

    /// <summary>Dataset 06 - Trending: deterministic exponential drift plus small noise. price_t = 100*exp(drift*t + smallNoise_t). Non-stationary in level (ADF/KPSS with constant-only regression must not find level-stationarity); DFA on log-returns should read close to the noise's own H (~0.5) since the drift is a deterministic mean removed by the return operator, not persistence.</summary>
    public static decimal[] Trending(int length = 120, ulong seed = 42UL, double drift = 0.01)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var series = new decimal[length];
        for (int i = 0; i < length; i++)
            series[i] = 100m * (decimal)Math.Exp(drift * i + 0.001 * (double)noise[i]);
        return series;
    }

    /// <summary>Dataset 07 - Structural Break: white-noise level series (Dataset 02's construction) with a single, one-time mean shift of +5 at the midpoint. Known, single breakpoint at length/2.</summary>
    public static decimal[] StructuralBreak(int length = 120, ulong seed = 42UL, decimal shift = 5m)
    {
        decimal[] series = WhiteNoise(length, seed);
        int breakIndex = length / 2;
        for (int i = breakIndex; i < length; i++)
            series[i] += shift;
        return series;
    }

    /// <summary>Dataset 08 - Variance Break: white-noise level series whose noise amplitude doubles at the midpoint (mean unchanged, variance step change). Known, single breakpoint at length/2.</summary>
    public static decimal[] VarianceBreak(int length = 120, ulong seed = 42UL)
    {
        decimal[] noise = GenerateGaussian(seed, length);
        var series = new decimal[length];
        int breakIndex = length / 2;
        for (int i = 0; i < length; i++)
        {
            decimal sigma = i < breakIndex ? 1.0m : 3.0m;
            series[i] = 100m + sigma * noise[i];
        }
        return series;
    }

    /// <summary>Dataset 09 - High Volatility: white-noise level series with a large amplitude (sigma=5). Same shape as Dataset 02, scaled for regime comparison purposes (e.g. VolatilityEvidence clustering / relative-volatility consumers).</summary>
    public static decimal[] HighVolatility(int length = 120, ulong seed = 42UL) =>
        WhiteNoise(length, seed, sigma: 5.0m);

    /// <summary>Dataset 10 - Low Volatility: white-noise level series with a tiny amplitude (sigma=0.01), just above the exact-constant degenerate case (Dataset 01).</summary>
    public static decimal[] LowVolatility(int length = 120, ulong seed = 42UL) =>
        WhiteNoise(length, seed, sigma: 0.01m);

    // ── Générateur déterministe (identique aux GoldenDataset existants : LCG 64-bit + Box-Muller) ──

    private static decimal[] GenerateGaussian(ulong seed, int n)
    {
        var z = new decimal[n];
        for (int i = 0; i < n; i += 2)
        {
            seed = seed * 6364136223846793005UL + 1442695040888963407UL;
            double u1 = (seed >> 11) / (double)(1UL << 53) + 1e-15;
            seed = seed * 6364136223846793005UL + 1442695040888963407UL;
            double u2 = (seed >> 11) / (double)(1UL << 53);
            double r = Math.Sqrt(-2.0 * Math.Log(u1));
            z[i] = (decimal)(r * Math.Cos(2.0 * Math.PI * u2));
            if (i + 1 < n)
                z[i + 1] = (decimal)(r * Math.Sin(2.0 * Math.PI * u2));
        }
        return z;
    }
}
