<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>True</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>IQIAIndicator</AssemblyName>
    <RootNamespace>IQIAIndicator</RootNamespace>
    <NoWarn>$(NoWarn);CA1416;CS8002</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <ATAS_BASE>C:\Program Files (x86)\ATAS Platform</ATAS_BASE>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OFT.Attributes">
      <HintPath>$(ATAS_BASE)\OFT.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="ATAS.DataFeedsCore">
      <HintPath>$(ATAS_BASE)\ATAS.DataFeedsCore.dll</HintPath>
    </Reference>
    <Reference Include="ATAS.Indicators">
      <HintPath>$(ATAS_BASE)\ATAS.Indicators.dll</HintPath>
    </Reference>
    <Reference Include="OFT.Rendering">
      <HintPath>$(ATAS_BASE)\OFT.Rendering.dll</HintPath>
    </Reference>
    <Reference Include="Utils.Common">
      <HintPath>$(ATAS_BASE)\Utils.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>

